version: '3.8'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    container_name: nextjs_frontend
    restart: unless-stopped
    env_file:
      - .env.local
