# Load environment variables from .env file
build:
	docker compose build

up:
	docker compose up --build -d

down:
	docker compose down --remove-orphans

test:
	docker compose exec frontend npm run test

ps:
	docker ps

%:
	@:
