# .github/workflows/backend.yml
name: Backend CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]      

jobs:
  call-backend-workflow:
    uses: imreg/taskmanager/backend/.github/workflows/laravel-tests.yml
