# .github/workflows/backend.yml
name: Backend CI

on:
  push:
    paths:
      - 'backend/**'
  pull_request:
    paths:
      - 'backend/**'

jobs:
  call-backend-workflow:
    uses: ./backend/.github/workflows/laravel-tests.yml

