# .github/workflows/backend.yml
name: Backend CI

#on:
#  push:
#    paths:
#      - 'backend/**'
#  pull_request:
#    paths:
#      - 'backend/**'

#jobs:
#  call-backend-workflow:
#    uses: imreg/taskmanager/backend/.github/workflows/laravel-tests.yml@main

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  laravel-tests:
    name: Laravel Tests
    uses: backend/.github/workflows/laravel-tests.yml # Reusable workflow call
    secrets: inherit # Inherit secrets from the caller workflow if needed.
