# .github/workflows/backend.yml
name: Backend CI

on:
  push:
    paths:
      - 'backend/**'
  pull_request:
    paths:
      - 'backend/**'

jobs:
  call-workflow-passing-data:
    uses: imreg/taskmanager/backend/.github/workflows/laravel-tests.yml@main # Reusable workflow call
    secrets: inherit # Inherit secrets from the caller workflow if needed.
