# .github/workflows/frontend.yml
name: Frontend CI

on:
  push:
    paths:
      - 'frontend/**'
  pull_request:
    paths:
      - 'frontend/**'

jobs:
  call-workflow-passing-data:
    uses: imreg/taskmanager/frontend/.github/workflows/nextjs-tests.yml@main # Reusable workflow call
    secrets: inherit # Inherit secrets from the caller workflow if needed.
